=== otmanel31/JavaBase/xml/xmlShemaValidation/repertoire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/repertoire" xmlns:tns="http://www.example.org/repertoire" elementFormDefault="qualified">
	<xs:element name="repertoire">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entree" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"></xs:maxLength>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="prenom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"></xs:maxLength>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="adresse">
								<xs:complexType>
									<xs:all>
										<xs:element name="rue" type="xs:string" />
										<xs:element name="ville" type="xs:string" />
										<xs:element name="CP" type="xs:string" />
										
									</xs:all>
									<xs:attribute name="codePays" type="xs:int"></xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="contact">
								<xs:complexType>
									<xs:all>
										<xs:element name="tel" type="xs:string" />
										<xs:element name="email" type="xs:string" />
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="no" type="xs:int"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== otmanel31/JavaBase/xml/xmlSax/repertoire.xml
<?xml version="1.0" encoding="UTF-8"?>
<repertoire xmlns="http://www.example.org/repertoire" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/repertoire repertoire.xsd ">
  <entree no="1">
    <nom>Courtalon</nom>
    <prenom>Vincent</prenom>    
    <adresse codePays="1">
	    <rue>221b baker street</rue>
	    <ville>Londre</ville>
	    <CP>75013</CP>
    </adresse>
    <contact>
	    <tel>01.02.03.04.05</tel>
	    <email>vincent@bob.com</email>
    </contact>
  </entree>
  <entree no="2">
    <nom>Bob</nom>
    <prenom>Joe</prenom>
    <adresse codePays="2">
	    <rue>221b rue de choisy</rue>
	    <ville>Paris</ville>
	    <CP>75013</CP>
    </adresse>
    <contact>
	    <tel>01.02.03.04.05</tel>
	    <email>bob@bob.com</email>
    </contact>
  </entree>
  <entree no="2">
    <nom>francky</nom>
    <prenom>bobby</prenom>
    <adresse codePays="2">
	    <rue>1 rue de la paix</rue>
	    <ville>Paris</ville>
	    <CP>75001</CP>
    </adresse>
    <contact>
	    <tel>01.02.03.04.05</tel>
	    <email>francky@bob.com</email>
    </contact>
  </entree>
</repertoire>
