=== otmanel31/JavaBase/xml/xmlExo/exportBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/exportBase" 
		xmlns:tns="http://www.example.org/exportBase" elementFormDefault="qualified">
	<xs:element name="data">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="table" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="columns">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="column" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="type" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rows" >
								<xs:complexType>
									<xs:sequence>
										<xs:element name="row" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cell" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
						<xs:attribute name="name" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== otmanel31/JavaBase/xml/xmlExo/sortie.xml
<?xml version="1.0" ?>
<data xmlns="http://www.example.org/exportBase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/exportBase exportBase.xsd">
<table name="client">
	<columns>
		<column name="id" type="INT"/>
		<column name="nom" type="VARCHAR"/>
		<column name="email" type="VARCHAR"/>
	</columns>
	<rows>
		<row>
		<cell name="id">1</cell>
		<cell name="nom">otman</cell>
		<cell name="email">o@o.fr</cell>
		</row>
	</rows>
</table>
<table name="produit">
	<columns>
		<column name="id" type="INT"/>
		<column name="nom" type="VARCHAR"/>
		<column name="prix" type="DOUBLE"/>
		<column name="poids" type="DOUBLE"/>
	</columns>
	<rows>
	<row><cell name="id">1</cell><cell name="nom">steak</cell><cell name="prix">10</cell><cell name="poids">25</cell></row><row><cell name="id">2</cell><cell name="nom">tofu</cell><cell name="prix">50</cell><cell name="poids">0.2</cell></row><row><cell name="id">3</cell><cell name="nom">kinoa des andes</cell><cell name="prix">49.99</cell><cell name="poids">1</cell></row><row><cell name="id">4</cell><cell name="nom">coca cola cherry</cell><cell name="prix">2.55</cell><cell name="poids">1</cell></row><row><cell name="id">6</cell><cell name="nom">produuit default</cell><cell name="prix">12.5</cell><cell name="poids">13.5</cell></row></rows></table></data>
